name: Deploy to staging
on:
    push:
        branches:
            - "main"

jobs:
    redeploy_everything:
        name: Deploying everything to the staging cluster
        runs-on: ubuntu-latest

        steps:
            - name: SSH into Server
              run: |
               echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
               chmod 600 ~/ssh_key
               ssh -i ~/ssh_key ubuntu@13.61.176.198 << 'EOF'
                 cd ci-cd-turborepo-cohort3 && git pull
                 pnpm install
                 pnpm run build
                 pm2 restart http-server
                 pm2 restart nextapp
                 pm2 restart ws
               EOF 
               



        

